### ISSUE TITLE
How would I construct a specific matrix?

### ISSUE THREAD

**Issue by langston-barrett** [coq-contribs/lin-alg#3]
Hi there,

As you'll soon deduce, I'm very new to coq. 

I'd like to prove the validity of some very elementary calculations with matrices, like
```
  (0 0) + (1 1) = (1 1)
  (0 0)   (1 1)   (1 1)
```
but I'm having trouble figuring out how to use this library to formulate any concrete examples of matrices.

Can you give me a hint or two? I'm happy to make a PR with this sort of calculation as an "example" once I figure out how to do it :)

I have tried the following:
```
Definition I2 (finite1 : fin 2) (finite2 : fin 2) : Nat :=
  (* First, extract the actual indices *)
  match finite1, finite2 return nat with
    | Build_finiteT ind1 _, Build_finiteT ind2 _ =>
      (* Then, return the appropriate value *)
      match ind1, ind2 return nat with
        | O, O => (S O)
        | (S O), (S O) => (S O)
        | _, _ => O
      end
  end.
```
But I'm having trouble promoting this into a `Map2`, `MAP2`, and `matrix`. This might not even be remotely the right direction.

**Comment by herbelin** [comment]
I think you can do, e.g.:

``` coq
Definition I2' : Map2 (fin 2) (fin 2) Nat.
exists I2.
intros [] [] [] []. unfold "='". simpl. now intros -> ->.
Qed.
```

**Comment by langston-barrett** [comment]
@herbelin That works perfectly for the identity matrix, but I guess I'm wondering more generally... Anyway, following our discussions on some other issues, I might start looking for some other algebra/linear algebra libraries! Thank you for your help.
